<a href="https://colab.research.google.com/github/gsingla21/Machine_Learning/blob/main/ML_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
import nltk
from nltk.corpus import *

In [ ]:
import os
dataset_dir=os.listdir("/content/drive/MyDrive/ML assignments/Assignment 1/Dataset")
data=[]
for i in range(len(dataset_dir)):
  f=open("/content/drive/MyDrive/ML assignments/Assignment 1/Dataset/"+dataset_dir[i],"r")
  text=f.read()
  data.append(text)
  f.close()

In [ ]:
for i in range(len(data)):
  print(dataset_dir[i],":")
  print(data[i])
  print()

1.txt :
The stemmed form of leafs is leaf.


2.txt :
The stemmed form of leaves is leav.


3.txt :
The lemmatized form of leafs is leaf.


4.txt :
The lemmatized form of leaves is leaf

5.txt :
I like fishing


6.txt :
I eat fish

7.txt :
','There are many fishes in pound '

8.txt :
0 This is introduction to NLP
1 It is likely to be useful, to people


9.txt :
2 Machine learning is the new electrcity
3 There would be less hype around AI and more ac...


10.txt :
4 python is the best tool!
5 R is good langauage
6 I like this book




**Method: 2**

In [ ]:
from nltk.corpus import PlaintextCorpusReader
dataset=[]
for i in range(len(dataset_dir)):
  a=(PlaintextCorpusReader("/content/drive/MyDrive/ML assignments/Assignment 1/Dataset/",dataset_dir[i]))
  dataset.append(a.raw())

In [ ]:
for i in range(len(dataset)):
  print(dataset_dir[i],":")
  print(dataset[i])
  print()

1.txt :
The stemmed form of leafs is leaf.


2.txt :
The stemmed form of leaves is leav.


3.txt :
The lemmatized form of leafs is leaf.


4.txt :
The lemmatized form of leaves is leaf

5.txt :
I like fishing


6.txt :
I eat fish

7.txt :
','There are many fishes in pound '

8.txt :
0 This is introduction to NLP
1 It is likely to be useful, to people


9.txt :
2 Machine learning is the new electrcity
3 There would be less hype around AI and more ac...


10.txt :
4 python is the best tool!
5 R is good langauage
6 I like this book




In [ ]:
from nltk.corpus import PlaintextCorpusReader
dataset=PlaintextCorpusReader("/content/drive/MyDrive/ML assignments/Assignment 1/Dataset/",".*")
print(dataset.raw())

The stemmed form of leafs is leaf.
4 python is the best tool!
5 R is good langauage
6 I like this book
The stemmed form of leaves is leav.
The lemmatized form of leafs is leaf.
The lemmatized form of leaves is leafI like fishing
I eat fish','There are many fishes in pound '0 This is introduction to NLP
1 It is likely to be useful, to people
2 Machine learning is the new electrcity
3 There would be less hype around AI and more ac...



# **Normalisation**
**1. Convert the text in same case, here lower case**

In [ ]:
lower_corpus=[]
for i in range(len(data)):
  lower_corpus.append(' '.join([word.lower() for word in data[i].split()]))

for i in range(len(lower_corpus)):
  print(dataset_dir[i],":")
  print(lower_corpus[i])
  print()

1.txt :
the stemmed form of leafs is leaf.

2.txt :
the stemmed form of leaves is leav.

3.txt :
the lemmatized form of leafs is leaf.

4.txt :
the lemmatized form of leaves is leaf

5.txt :
i like fishing

6.txt :
i eat fish

7.txt :
','there are many fishes in pound '

8.txt :
0 this is introduction to nlp 1 it is likely to be useful, to people

9.txt :
2 machine learning is the new electrcity 3 there would be less hype around ai and more ac...

10.txt :
4 python is the best tool! 5 r is good langauage 6 i like this book



**2. Removing numbers, special symbols, urls from text**

In [ ]:
alpha_corpus=[]
for i in range(len(lower_corpus)):
  alpha_corpus.append(' '.join([words for words in lower_corpus[i].split(' ') if words.isalpha()]))

for i in range(len(lower_corpus)):
  print(dataset_dir[i],":")
  print(alpha_corpus[i])
  print()

1.txt :
the stemmed form of leafs is

2.txt :
the stemmed form of leaves is

3.txt :
the lemmatized form of leafs is

4.txt :
the lemmatized form of leaves is leaf

5.txt :
i like fishing

6.txt :
i eat fish

7.txt :
are many fishes in pound

8.txt :
this is introduction to nlp it is likely to be to people

9.txt :
machine learning is the new electrcity there would be less hype around ai and more

10.txt :
python is the best r is good langauage i like this book



**3. Tokenization**

Method 3.1

In [ ]:
from nltk.tokenize import word_tokenize
tokenized_corpus=[]
for i in range(len(alpha_corpus)):
  tokenized_corpus.append(word_tokenize(alpha_corpus[i]))
  
for i in range(len(tokenized_corpus)):
  print(dataset_dir[i],":")
  print(tokenized_corpus[i])
  print()

1.txt :
['the', 'stemmed', 'form', 'of', 'leafs', 'is']

2.txt :
['the', 'stemmed', 'form', 'of', 'leaves', 'is']

3.txt :
['the', 'lemmatized', 'form', 'of', 'leafs', 'is']

4.txt :
['the', 'lemmatized', 'form', 'of', 'leaves', 'is', 'leaf']

5.txt :
['i', 'like', 'fishing']

6.txt :
['i', 'eat', 'fish']

7.txt :
['are', 'many', 'fishes', 'in', 'pound']

8.txt :
['this', 'is', 'introduction', 'to', 'nlp', 'it', 'is', 'likely', 'to', 'be', 'to', 'people']

9.txt :
['machine', 'learning', 'is', 'the', 'new', 'electrcity', 'there', 'would', 'be', 'less', 'hype', 'around', 'ai', 'and', 'more']

10.txt :
['python', 'is', 'the', 'best', 'r', 'is', 'good', 'langauage', 'i', 'like', 'this', 'book']



Method 3.2

In [ ]:
tokenized_corpus1=[]
for i in range(len(alpha_corpus)):
  tokenized_corpus1.append([word for word in alpha_corpus[i].split()])
for i in range(len(tokenized_corpus1)):
  print(dataset_dir[i],":")
  print(tokenized_corpus1[i])
  print()

1.txt :
['the', 'stemmed', 'form', 'of', 'leafs', 'is']

2.txt :
['the', 'stemmed', 'form', 'of', 'leaves', 'is']

3.txt :
['the', 'lemmatized', 'form', 'of', 'leafs', 'is']

4.txt :
['the', 'lemmatized', 'form', 'of', 'leaves', 'is', 'leaf']

5.txt :
['i', 'like', 'fishing']

6.txt :
['i', 'eat', 'fish']

7.txt :
['are', 'many', 'fishes', 'in', 'pound']

8.txt :
['this', 'is', 'introduction', 'to', 'nlp', 'it', 'is', 'likely', 'to', 'be', 'to', 'people']

9.txt :
['machine', 'learning', 'is', 'the', 'new', 'electrcity', 'there', 'would', 'be', 'less', 'hype', 'around', 'ai', 'and', 'more']

10.txt :
['python', 'is', 'the', 'best', 'r', 'is', 'good', 'langauage', 'i', 'like', 'this', 'book']



**4. Stopword Removal**

In [ ]:
nltk.download('stopwords')
from nltk.corpus import stopwords
sw=stopwords.words(fileids="english")
print("stopwords available:\n{}".format(sw))
tokenized_corpus_nsw=[]
for i in range(len(tokenized_corpus)):
  tokenized_corpus_nsw.append([word for word in tokenized_corpus[i] if word not in sw])
print("tokenized corpus without stopwords:")
for i in range(len(tokenized_corpus_nsw)):
  print(dataset_dir[i],":")
  print(tokenized_corpus_nsw[i])
  print()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
stopwords available:
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all

**5. Stemming**

In [ ]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()
tokenized_corpus_nsw_stem=[]
for i in range(len(tokenized_corpus_nsw)):
  tokenized_corpus_nsw_stem.append([ps.stem(word) for word in tokenized_corpus_nsw[i]])
for i in range(len(tokenized_corpus_nsw_stem)):
  print(dataset_dir[i],":")
  print(tokenized_corpus_nsw_stem[i])
  print()

1.txt :
['stem', 'form', 'leaf']

2.txt :
['stem', 'form', 'leav']

3.txt :
['lemmat', 'form', 'leaf']

4.txt :
['lemmat', 'form', 'leav', 'leaf']

5.txt :
['like', 'fish']

6.txt :
['eat', 'fish']

7.txt :
['mani', 'fish', 'pound']

8.txt :
['introduct', 'nlp', 'like', 'peopl']

9.txt :
['machin', 'learn', 'new', 'electrc', 'would', 'less', 'hype', 'around', 'ai']

10.txt :
['python', 'best', 'r', 'good', 'langauag', 'like', 'book']



# **BoW**

Method 1 *Using CountVectorizer*

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer(ngram_range=(1,1))   #ngrams represents the combination of words to be defined as singla differential entity
BoW=[]                                          #would contain bag of words
feature_matrix=[]
data1=[]
for i in range(len(lower_corpus)):
  input=lower_corpus[i]
  input=[input]
  data1.append(input)                           #data1 now contain data as list of lists.

for i in range(len(data1)):
  vectorizer.fit(data1[i])
  vector=vectorizer.transform(data1[i])
  BoW.append(vectorizer.vocabulary_)
  feature_matrix.append(vector.toarray())
print("Feature Matrix:")
for i in range(len(feature_matrix)):
  for j in range(len(feature_matrix[i])):
    print(feature_matrix[i][j])
  print("\n")
print("Bag of Word:\n",BoW)

Feature Matrix:
[1 1 1 1 1 1 1]


[1 1 1 1 1 1 1]


[1 1 1 1 1 1 1]


[1 1 1 1 1 1 1]


[1 1]


[1 1]


[1 1 1 1 1 1]


[1 1 2 1 1 1 1 1 3 1]


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


[1 1 1 2 1 1 1 1 1 1]


Bag of Word:
 [{'the': 6, 'stemmed': 5, 'form': 0, 'of': 4, 'leafs': 3, 'is': 1, 'leaf': 2}, {'the': 6, 'stemmed': 5, 'form': 0, 'of': 4, 'leaves': 3, 'is': 1, 'leav': 2}, {'the': 6, 'lemmatized': 4, 'form': 0, 'of': 5, 'leafs': 3, 'is': 1, 'leaf': 2}, {'the': 6, 'lemmatized': 4, 'form': 0, 'of': 5, 'leaves': 3, 'is': 1, 'leaf': 2}, {'like': 1, 'fishing': 0}, {'eat': 0, 'fish': 1}, {'there': 5, 'are': 0, 'many': 3, 'fishes': 1, 'in': 2, 'pound': 4}, {'this': 7, 'is': 2, 'introduction': 1, 'to': 8, 'nlp': 5, 'it': 3, 'likely': 4, 'be': 0, 'useful': 9, 'people': 6}, {'machine': 10, 'learning': 8, 'is': 7, 'the': 13, 'new': 12, 'electrcity': 5, 'there': 14, 'would': 15, 'be': 4, 'less': 9, 'hype': 6, 'around': 3, 'ai': 1, 'and': 2, 'more': 11, 'ac': 0}, {'python': 6, 'is': 3, 'the': 7, 'b

Method 2 *Without using in-built function CountVectorizer*

In [ ]:
unique_words=set()               #set() function for no duplicacy
for text in data:
  for word in text.split(' '):
    if len(word)>2:
      unique_words.add(word)
vocabulary={}
for index,word in enumerate(sorted(list(unique_words))):
  vocabulary[word]=index

text_vector=[]
for text in data:
  text_token=nltk.word_tokenize(text)
  sent_vec=[]
  for token in vocabulary:
    if token in text_token:
      sent_vec.append(1)
    else:
      sent_vec.append(0)
  text_vector.append(sent_vec)
import numpy as np
text_vector=np.asarray(text_vector)
print("Text Vector:\n",text_vector)

Text Vector:
 [[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
  0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
  1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0
  0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
  0 1 0 1 1 0 0 0]]


# **TF-IDF**

Using TfidfVectorizer

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
vectorizer.fit(data)
print(vectorizer.vocabulary_)
print(vectorizer.idf_)

{'the': 40, 'stemmed': 39, 'form': 13, 'of': 35, 'leafs': 22, 'is': 18, 'leaf': 21, 'leaves': 25, 'leav': 24, 'lemmatized': 26, 'like': 28, 'fishing': 12, 'eat': 8, 'fish': 10, 'there': 41, 'are': 3, 'many': 31, 'fishes': 11, 'in': 16, 'pound': 37, 'this': 42, 'introduction': 17, 'to': 43, 'nlp': 34, 'it': 19, 'likely': 29, 'be': 5, 'useful': 45, 'people': 36, 'machine': 30, 'learning': 23, 'new': 33, 'electrcity': 9, 'would': 46, 'less': 27, 'hype': 15, 'around': 4, 'ai': 1, 'and': 2, 'more': 32, 'ac': 0, 'python': 38, 'best': 6, 'tool': 44, 'good': 14, 'langauage': 20, 'book': 7}
[2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 2.29928298
 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809
 2.70474809 1.78845736 2.70474809 2.70474809 2.70474809 2.70474809
 1.31845373 2.70474809 2.70474809 2.01160091 2.29928298 2.70474809
 2.70474809 2.29928298 2.29928298 2.70474809 2.29928298 2.70474809
 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 1.78845736
 2.704748

Without in-built function TfidfVectorizer

In [ ]:
import math
def idf(corpus,unique_words):
  idf_dict={}
  n=len(corpus)
  for i in unique_words:
    count=0
    for text in corpus:
      if i in text.split():
        count=count+1
      idf_dict[i]=(math.log((1+n)/(count+1)))+1      #extra 1 for avoiding denominator eing zero
  return idf_dict

def fit(whole_data):
  unique_words=set()
  if isinstance(whole_data,(list,)):
    for x in whole_data:
      for y in x.split():
        if len(y)<2:                                 #removing words of size<2
          continue
        unique_words.add(y)
        vocab = {j:i for i,j in enumerate(unique_words)}
        Idf_values_of_all_unique_words=idf(whole_data,unique_words)
  return vocab, Idf_values_of_all_unique_words
Vocabulary, idf_of_vocabulary=fit(data)
print(list(Vocabulary.keys()))
print(list(idf_of_vocabulary.values()))

['good', 'fish', 'lemmatized', 'hype', 'in', 'would', 'stemmed', 'useful,', 'less', 'python', 'is', 'NLP', 'There', 'best', 'pound', 'are', 'more', 'around', 'of', 'form', 'fishing', 'This', "','There", 'eat', 'leav.', 'The', 'leaf.', 'leaf', 'new', 'langauage', 'fishes', 'the', 'many', 'It', 'book', 'leaves', 'be', 'introduction', 'learning', 'AI', 'this', 'electrcity', 'to', 'like', 'likely', 'ac...', 'people', 'and', 'leafs', 'tool!', 'Machine']
[2.7047480922384253, 2.7047480922384253, 2.2992829841302607, 2.7047480922384253, 2.7047480922384253, 2.7047480922384253, 2.2992829841302607, 2.7047480922384253, 2.7047480922384253, 2.7047480922384253, 1.3184537311185345, 2.7047480922384253, 2.7047480922384253, 2.7047480922384253, 2.7047480922384253, 2.7047480922384253, 2.7047480922384253, 2.7047480922384253, 1.7884573603642702, 1.7884573603642702, 2.7047480922384253, 2.7047480922384253, 2.7047480922384253, 2.7047480922384253, 2.7047480922384253, 1.7884573603642702, 2.2992829841302607, 2.7047

In [ ]:
from scipy.sparse import csr_matrix
import collections
import numpy as np
from sklearn.preprocessing import normalize
def transform(dataset,vocabulary,idf_values):
  sparse_matrix=csr_matrix((len(dataset),len(vocabulary)),dtype=np.float64)
  for row in range(0,len(dataset)):
    word_count=collections.Counter(dataset[row].split())
    for word in dataset[row].split():
      if word in list(vocabulary.keys()):
        tf_idf_val=(word_count[word]/len(dataset[row].split()))*idf_values[word]
        sparse_matrix[row,vocabulary[word]]=tf_idf_val
  print("Normal Form")
  print(normalize(sparse_matrix, norm='l2', axis=1, copy=True, return_norm=False))
  output=normalize(sparse_matrix, norm='l2', axis=1, copy=True, return_norm=False)
  return output
final_output=transform(data,Vocabulary,idf_of_vocabulary)
print(final_output)

Normal Form
  (0, 6)	0.44091467321457456
  (0, 10)	0.25282907759375284
  (0, 18)	0.3429578255681724
  (0, 19)	0.3429578255681724
  (0, 25)	0.3429578255681724
  (0, 26)	0.44091467321457456
  (0, 48)	0.44091467321457456
  (1, 6)	0.42533300936984214
  (1, 10)	0.24389424748588198
  (1, 18)	0.33083789879875186
  (1, 19)	0.33083789879875186
  (1, 24)	0.5003379982365557
  (1, 25)	0.33083789879875186
  (1, 35)	0.42533300936984214
  (2, 2)	0.44091467321457456
  (2, 10)	0.25282907759375284
  (2, 18)	0.3429578255681724
  (2, 19)	0.3429578255681724
  (2, 25)	0.3429578255681724
  (2, 26)	0.44091467321457456
  (2, 48)	0.44091467321457456
  (3, 2)	0.4253330093698421
  (3, 10)	0.24389424748588193
  (3, 18)	0.3308378987987518
  (3, 19)	0.3308378987987518
  :	:
  (8, 5)	0.26097186055143445
  (8, 8)	0.26097186055143445
  (8, 10)	0.12721307549799496
  (8, 12)	0.26097186055143445
  (8, 16)	0.26097186055143445
  (8, 17)	0.26097186055143445
  (8, 28)	0.26097186055143445
  (8, 31)	0.22184992385229263
  (8, 36

/usr/local/lib/python3.7/dist-packages/scipy/sparse/_index.py:84: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])


In [ ]:
for i in range(len(dataset_dir)):
  print(final_output[i].toarray())

[[0.         0.         0.         0.         0.         0.
  0.44091467 0.         0.         0.         0.25282908 0.
  0.         0.         0.         0.         0.         0.
  0.34295783 0.34295783 0.         0.         0.         0.
  0.         0.34295783 0.44091467 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.44091467 0.         0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.42533301 0.         0.         0.         0.24389425 0.
  0.         0.         0.         0.         0.         0.
  0.3308379  0.3308379  0.         0.         0.         0.
  0.500338   0.3308379  0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.42533301
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.       

# **Working with HTML**

In [ ]:
!pip install bs4
import urllib.request as urllib2
from bs4 import BeautifulSoup

In [ ]:
response=urllib2.urlopen('https://en.wikipedia.org/wiki/Natural_language_processing')
html_doc=response.read()

*Parsing*

In [ ]:
soup=BeautifulSoup(html_doc,'html.parser')

Formatting the parsed file

In [ ]:
strhtm=soup.prettify()
print(strhtm)

<!DOCTYPE html>
<html class="client-nojs" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Natural language processing - Wikipedia
  </title>
  <script>
   document.documentElement.className="client-js";RLCONF={"wgBreakFrames":!1,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"YEfOges9y84yWmZqRxpq9AAAAEE","wgCSPNonce":!1,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":!1,"wgNamespaceNumber":0,"wgPageName":"Natural_language_processing","wgTitle":"Natural language processing","wgCurRevisionId":1011165445,"wgRevisionId":1011165445,"wgArticleId":21652,"wgIsArticle":!0,"wgIsRedirect":!1,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["CS1 maint: location","Articles with short description","Short description matches Wikidata","Commons link from Wikidat

In [ ]:
data=[]
for x in soup.find_all('p'): 
  data.append(x.text)
print(data)

['Natural language processing (NLP) is a subfield of linguistics, computer science, and artificial intelligence concerned with the interactions between computers and human language, in particular how to program computers to process and analyze large amounts of natural language data.  The result is a computer capable of "understanding" the contents of documents, including the contextual nuances of the language within them. The technology can then accurately extract information and insights contained in the documents as well as categorize and organize the documents themselves. \n', 'Challenges in natural language processing frequently involve speech recognition, natural language understanding, and natural-language generation.\n', 'Natural language processing has its roots in the 1950s. Already in 1950, Alan Turing published an article titled "Computing Machinery and Intelligence" which proposed what is now called the Turing test as a criterion of intelligence, a task that involves the au

# **Normalization**
*Get whole data in same case (in this case lower case)*

In [ ]:
lower_data=[]
for i in range(len(data)):
  lower_data.append(' '.join([word.lower() for word in data[i].split()]))
print(lower_data)

['natural language processing (nlp) is a subfield of linguistics, computer science, and artificial intelligence concerned with the interactions between computers and human language, in particular how to program computers to process and analyze large amounts of natural language data. the result is a computer capable of "understanding" the contents of documents, including the contextual nuances of the language within them. the technology can then accurately extract information and insights contained in the documents as well as categorize and organize the documents themselves.', 'challenges in natural language processing frequently involve speech recognition, natural language understanding, and natural-language generation.', 'natural language processing has its roots in the 1950s. already in 1950, alan turing published an article titled "computing machinery and intelligence" which proposed what is now called the turing test as a criterion of intelligence, a task that involves the automate

*Remove any alpha characters for clean functioning*

In [ ]:
alpha_data=[]
for i in range(len(lower_data)):
  alpha_data.append(' '.join([word for word in lower_data[i].split() if word.isalpha()]))
print(alpha_data)

['natural language processing is a subfield of computer and artificial intelligence concerned with the interactions between computers and human in particular how to program computers to process and analyze large amounts of natural language the result is a computer capable of the contents of including the contextual nuances of the language within the technology can then accurately extract information and insights contained in the documents as well as categorize and organize the documents', 'challenges in natural language processing frequently involve speech natural language and', 'natural language processing has its roots in the already in alan turing published an article titled machinery and which proposed what is now called the turing test as a criterion of a task that involves the automated interpretation and generation of natural but at the time not articulated as a problem separate from artificial', 'the premise of symbolic nlp is by john chinese room given a collection of rules a 

*Tokenization*

In [ ]:
from nltk.tokenize import word_tokenize
tokenized_data=[]
for i in range(len(alpha_data)):
  tokenized_data.append(word_tokenize(alpha_data[i]))
print(tokenized_data)

[['natural', 'language', 'processing', 'is', 'a', 'subfield', 'of', 'computer', 'and', 'artificial', 'intelligence', 'concerned', 'with', 'the', 'interactions', 'between', 'computers', 'and', 'human', 'in', 'particular', 'how', 'to', 'program', 'computers', 'to', 'process', 'and', 'analyze', 'large', 'amounts', 'of', 'natural', 'language', 'the', 'result', 'is', 'a', 'computer', 'capable', 'of', 'the', 'contents', 'of', 'including', 'the', 'contextual', 'nuances', 'of', 'the', 'language', 'within', 'the', 'technology', 'can', 'then', 'accurately', 'extract', 'information', 'and', 'insights', 'contained', 'in', 'the', 'documents', 'as', 'well', 'as', 'categorize', 'and', 'organize', 'the', 'documents'], ['challenges', 'in', 'natural', 'language', 'processing', 'frequently', 'involve', 'speech', 'natural', 'language', 'and'], ['natural', 'language', 'processing', 'has', 'its', 'roots', 'in', 'the', 'already', 'in', 'alan', 'turing', 'published', 'an', 'article', 'titled', 'machinery', 'a

*Remove Stopwords*

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from nltk.corpus import stopwords
stop=stopwords.words(fileids='english')
tokenized_data_nostop=[]
for i in range(len(tokenized_data)):
  tokenized_data_nostop.append([word for word in tokenized_data[i] if word not in stop])
print(tokenized_data_nostop)

[['natural', 'language', 'processing', 'subfield', 'computer', 'artificial', 'intelligence', 'concerned', 'interactions', 'computers', 'human', 'particular', 'program', 'computers', 'process', 'analyze', 'large', 'amounts', 'natural', 'language', 'result', 'computer', 'capable', 'contents', 'including', 'contextual', 'nuances', 'language', 'within', 'technology', 'accurately', 'extract', 'information', 'insights', 'contained', 'documents', 'well', 'categorize', 'organize', 'documents'], ['challenges', 'natural', 'language', 'processing', 'frequently', 'involve', 'speech', 'natural', 'language'], ['natural', 'language', 'processing', 'roots', 'already', 'alan', 'turing', 'published', 'article', 'titled', 'machinery', 'proposed', 'called', 'turing', 'test', 'criterion', 'task', 'involves', 'automated', 'interpretation', 'generation', 'natural', 'time', 'articulated', 'problem', 'separate', 'artificial'], ['premise', 'symbolic', 'nlp', 'john', 'chinese', 'room', 'given', 'collection', 'ru

*Stemming*

In [ ]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()
tokenized_data_nostop_stem=[]
for i in range(len(tokenized_data_nostop)):
  tokenized_data_nostop_stem.append([ps.stem(word) for word in tokenized_data_nostop[i]])
print(tokenized_data_nostop_stem)

[['natur', 'languag', 'process', 'subfield', 'comput', 'artifici', 'intellig', 'concern', 'interact', 'comput', 'human', 'particular', 'program', 'comput', 'process', 'analyz', 'larg', 'amount', 'natur', 'languag', 'result', 'comput', 'capabl', 'content', 'includ', 'contextu', 'nuanc', 'languag', 'within', 'technolog', 'accur', 'extract', 'inform', 'insight', 'contain', 'document', 'well', 'categor', 'organ', 'document'], ['challeng', 'natur', 'languag', 'process', 'frequent', 'involv', 'speech', 'natur', 'languag'], ['natur', 'languag', 'process', 'root', 'alreadi', 'alan', 'ture', 'publish', 'articl', 'titl', 'machineri', 'propos', 'call', 'ture', 'test', 'criterion', 'task', 'involv', 'autom', 'interpret', 'gener', 'natur', 'time', 'articul', 'problem', 'separ', 'artifici'], ['premis', 'symbol', 'nlp', 'john', 'chines', 'room', 'given', 'collect', 'rule', 'chines', 'question', 'match', 'comput', 'emul', 'natur', 'languag', 'understand', 'nlp', 'appli', 'rule', 'data', 'confront'], [

**Bag of Words**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer(ngram_range=(1,1))
BoW=[]
feature_matrix=[]
data1=[]
for i in range(len(lower_data)):
  input=lower_data[i]
  input=[input]
  data1.append(input)

for i in range(len(data1)):
  vectorizer.fit(data1[i])
  vector=vectorizer.transform(data1[i])
  BoW.append(vectorizer.vocabulary_)
  feature_matrix.append(vector.toarray())
print("Feature Matrix:")
for i in range(len(feature_matrix)):
  for j in range(len(feature_matrix[i])):
    print(feature_matrix[i][j])
  print("\n")
print("Bag of Word:\n",BoW)


Feature Matrix:
[1 1 1 5 1 2 1 1 1 1 2 2 1 1 1 1 1 3 1 1 1 2 1 1 1 1 1 2 4 1 1 2 1 1 5 1 1
 1 1 1 1 1 1 1 8 1 1 1 2 1 1 1 1]


[1 1 1 1 1 1 3 3 1 1 1 1]


[1 1 1 1 1 2 1 1 1 2 1 1 1 1 1 1 1 1 1 2 3 1 1 1 1 2 1 2 1 1 2 1 1 1 1 1 1
 1 1 1 4 1 1 2 1 1]


[1 1 1 2 2 1 1 1 1 1 1 1 2 1 1 1 1 1 2 2 1 1 1 1 1 1 2 1 1 1 1 3 1 1 1 1 2]


[2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 4 1 1 2 1 2 2 1 1 2 6 1 1 4 1 1
 1 1 1 1 1 1 1 8 1 1 1 1 3 1 1 1 1 2 1 1 1 1]


[1 1 1 1 2 1 1 1 1 1 1 1 1 5 3 2 1 2 1 1 2 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1 1
 2 1 1]


[1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 2 1 1 1 1 1 2 1 1 1]


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 4 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 2 1 5 1 1 1 1 1 1]


[1 2 1 1 1 2 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 2 1 1 1 3 1 1 1 1 1 1 1 2
 1 2 1 1 4 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 2 3 1 1 2 1 1 1 1]


[1 2 2 2 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

**TF-Idf**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
vectorizer.fit(data)
print(vectorizer.vocabulary_)
print(vectorizer.idf_)

{'natural': 299, 'language': 254, 'processing': 347, 'nlp': 307, 'is': 248, 'subfield': 429, 'of': 316, 'linguistics': 268, 'computer': 115, 'science': 389, 'and': 51, 'artificial': 67, 'intelligence': 235, 'concerned': 118, 'with': 508, 'the': 450, 'interactions': 237, 'between': 80, 'computers': 116, 'human': 218, 'in': 221, 'particular': 331, 'how': 216, 'to': 469, 'program': 351, 'process': 345, 'analyze': 50, 'large': 255, 'amounts': 47, 'data': 135, 'result': 381, 'capable': 91, 'understanding': 486, 'contents': 125, 'documents': 155, 'including': 224, 'contextual': 128, 'nuances': 313, 'within': 509, 'them': 451, 'technology': 444, 'can': 90, 'then': 453, 'accurately': 27, 'extract': 181, 'information': 228, 'insights': 231, 'contained': 123, 'as': 68, 'well': 500, 'categorize': 94, 'organize': 324, 'themselves': 452, 'challenges': 96, 'frequently': 194, 'involve': 246, 'speech': 414, 'recognition': 366, 'generation': 200, 'has': 208, 'its': 250, 'roots': 387, '1950s': 9, 'alrea